# .github/workflows/build-distribution.yml
name: Build Distribution

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - uses: enyachoke/ozone-distro-builder@main
        with:
          registry: ghcr.io
          image-name: ${{ github.repository_owner }}/openmrs-distro-his
          registry-username: ${{ github.actor }}
          registry-password: ${{ secrets.GITHUB_TOKEN }}